name: Continous integration
on: [push]
jobs:
  Run-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9.6
      uses: actions/setup-python@v2
      with:
        python-version: "3.9.6"
    - name: Install
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: |
        nosetests tests
    - name: Run notebooks
      run: |
        PYTHONPATH=`pwd`
        export PYTHONPATH
        bash ./test_notebooks.sh
